# Generated by Django 4.1.9 on 2023-06-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("prd_id", models.IntegerField(primary_key=True, serialize=False)),
                ("prd_name", models.CharField(max_length=255)),
                ("prd_qnt", models.IntegerField()),
                ("prd_price", models.IntegerField()),
            ],
        ),
    ]
